### ISSUE TITLE
Tooltip positioning error

### ISSUE THREAD

**Issue by laytong** [brownieboy/react-bootstrap-slider#1]
<img width="73" alt="screen shot 2016-05-18 at 14 21 39" src="https://cloud.githubusercontent.com/assets/9656959/15375460/09b1394e-1d04-11e6-9de0-a24ea83adae2.png">

On first render i'm seeing the tooltip floating too far to the right. If I use the https://github.com/seiyria/bootstrap-slider directly in a setTimeout() during the onComponentDidMount method it renders in the right place. I'm willing to bet calling relayout would fix the tooltip. 

As soon as I click/drag the slider the tooltip re-renders the tooltip in the right position

**Comment by brownieboy** [comment]
I'm not seeing that in my own test.  Do you have some sample code?

Also, is it with any particular browser/os combination?

**Comment by laytong** [comment]
I'm on vacation at the moment, but will get back to you shortly. Try putting the slider inside a table cell. I think this is the cause?
i.e. 
```
<table>
  <tbody>
    <tr>
      <td>
        <ReactBootstrapSlider />
     </td>
    </tr>
  </tbody>
</table>
```

**Comment by laytong** [comment]
I think it might be being caused by the outdated version of bootstrap that we are stuck to using 😢

**Comment by brownieboy** [comment]
I still cannot reproduce.

I've updated the Demo file (the one in the /src folder) to display the horizontal slider inside a table cell.  Checkout the tooltip-error branch.
