### ISSUE TITLE
Upgrade "bootstrap-slider": "^7.1.0", to "9.2.0"

### ISSUE THREAD

**Issue by tomers** [brownieboy/react-bootstrap-slider#11]
Hi,

Is it possible to upgrade version of bootstrap-slider to 9.2.0 in order to include the Range Highlight feature? https://github.com/seiyria/bootstrap-slider/commit/17b4ae70baaedf9cfd1e2d64e8c6d996d69eacff

Thanks!

**Comment by brownieboy** [comment]
I will take a look.

**Comment by brownieboy** [comment]
Just updated NPM package to 1.1.0, which includes the 9.2 upgrade to seiyria's package.

The Range Highlight feature appears to be working fine, and I've added it to the demo code.  Check app.jsx file in src/js for an example, but basically, you just add the prop as you'd expect:

`           rangeHighlights = {[
              { "start": 1000, "end": 5000 },
              { "start": 12000, "end": 17000 }
            ]} `
