### ISSUE TITLE
Readme lacks information to use bootstrap-slider.min.css

### ISSUE THREAD

**Issue by tomers** [brownieboy/react-bootstrap-slider#13]
I spent quite some time trying to understand why the component is not visible in my project.
Eventually I figured I should use the following code in `app.js`:

`import BootstrapSlider from 'bootstrap-slider/dist/css/bootstrap-slider.min.css';`

Or in `index.html`:

`<link rel="stylesheet" href="bootstrap-slider/dist/css/bootstrap-slider.min.css" />`

Could you please add this information to Readme?

**Comment by brownieboy** [comment]
Sure

**Comment by brownieboy** [comment]
Just updated npm package to version 1.1.0, which includes this documentation update.

**Comment by tomers** [comment]
Thanks! Minor typo there: "Or you can add simply add it ..."
