### ISSUE TITLE
Add option to handle change on mouse up

### ISSUE THREAD

**Issue by jeffling** [brownieboy/react-bootstrap-slider#14]
Right now, if you hold your mouse and drag, `handleChange` gets called on every single mouse movement. This causes some performance issues, as well as janky behaviour if you don't debounce the handleChange callback, especially with multiple values. 

Proposal: Call handle change on mouse up as opposed to on every single movement

**Comment by brownieboy** [comment]
I've now changed the main slider trigger event from "change" to "slideStop" (mouseup equivalent) and have just published to npmjs as version 1.1.1.

Many thanks for the tip.

**Comment by brownieboy** [comment]
On reflection, I've not implemented this in a very smart way at all.  Rather than remapping the handleChange event to use slideStop, I should have added an extra handleSlideStop option.  I'll look at doing that now.

**Comment by jeffling** [comment]
handleSlideStop solution sounds good to me. There may be cases where people do want to render `change`as well, for example updating numbers as we slide. Then we can act on the value change for more render-heavy things (ie. re-rendering the value on the slider itself) on `handleSlideStop`.

**Comment by brownieboy** [comment]
Just released 1.1.2 which adds `slideStop` as a separate event and reverted the `handleChange` remapping from 1.1.1.
