### ISSUE TITLE
Slider appears in conditional code

### ISSUE THREAD

**Issue by ir-fuel** [brownieboy/react-bootstrap-slider#15]
I have a render call which only generates the slider element in an `else` clause.
However as soon as I render my component a slider appears on my screen, and every time the render is retriggered (due to state updates etc) an extra slider appears.

**Comment by brownieboy** [comment]
Post your code somewhere that we can see it.

**Comment by brownieboy** [comment]
Unable to reproduce.  Further information that I requested was not supplied, so I'm closing this.  Post some code and I'll reopen.
