### ISSUE TITLE
Using slider as form input

### ISSUE THREAD

**Issue by ckozin** [brownieboy/react-bootstrap-slider#17]
In [seiyria's Bootstrap Slider](https://github.com/seiyria/bootstrap-slider) other attributes can be supplied using the API format, for example name:

```
<input
type="text"
id="id-01"
name="somename"
data-provide="slider"
data-slider-ticks="[1, 2, 3]"
data-slider-min="1"
data-slider-max="3"
data-slider-step="1"
data-slider-value="3"
>
```

If using the component as a form input field, is there a way to send an id and/or name attribute so that it is attached to the `input` rather than the `div`?

The above example is then displayed in the code as:
    `<input type="text" id="id-01" name="somename" data-provide="slider" data-slider-ticks="[1, 2, 3]" data-slider-min="1" data-slider-max="3" data-slider-step="1" data-slider-value="3" data-value="1" value="1" style="display: none;">`

**Comment by biera** [comment]
@ckozin +1
I also want to use the component as form field. Is there a way to provide name attribute to rendered input element?

**Comment by brownieboy** [comment]
Sorry, guys, but I'm not quite getting what the requirement is here.  Could one (or both) of you post some application code that shows me what you're trying to do?

**Comment by biera** [comment]
The **Slider** component renders non-visible input HTML element which holds the value of the slider's value, however there is no way to provide a **name** attribute to that input. If you embed **Slider** component in form HTML element it's value is not sent to the server when you submit the form because input element is not named. And that's the expected behavior according to [W3 specs](https://www.w3.org/TR/html401/interact/forms.html#successful-controls).

Hope, it's clear enough now ;)

**Comment by ckozin** [comment]
When you use the Slider component with the code below:
`    var refKey = multiradio.node + "-" + multiradio.number; `
`<ReactBootstrapSlider
          max={7}
          min={1}
          step={1}
          ticks={[1, 2, 3, 4, 5, 6, 7]}
          tooltip="hide"
          name="answer"
          id={refKey}
          change={this.changeValue}
          value={this.state.currentValue}
        />`

The slider div is rendered as:
`<div class="slider slider-horizontal" id="111-2">`

The rendered input element is:
`<input data-value="5" value="5" style="display: none;">`

I am using this component as a survey and have multiple sliders for a section. The issue I am running into is that although I can change the value, all of the sliders change for that value. I need to tie the value to the id to prevent all of the rendered sliders from being assigned the same value.

<img width="528" alt="react-bootstrap-slider-same-value" src="https://cloud.githubusercontent.com/assets/16491302/20489768/b787ca70-afd9-11e6-9b3c-2f5c59399787.png">

**Comment by brownieboy** [comment]
@ckozin,

> although I can change the value, all of the sliders change for that value

That shouldn't be happening, and I'm really not sure why it is.

How are you adding the multiple ReactBootstrapSlider components to your Section?  Can I see that code, please?

The only thing that I can think of is that you've bound each ReactBootstrapSlider component to the same set of handler events (change, value etc), in which case, yes, they'll all change together.  Each of your components has to have its own set of handlers.  Something like this:

````Javascript
constructor(props) {
    super(props);
    this.state = {
        firstComponentValue: 4;
        secondComponentValue: 3;
    }
}

firstComponentChangeValue(e) {
      this.setState({ firstComponentCurrentValue: e.target.value });
}

secondComponentChangeValue(e) {
      this.setState({ secondComponentCurrentValue: e.target.value });
}

render() {
    <ReactBootstrapSlider max={7} min={1} step={1} ticks={[1, 2, 3, 4, 5, 6, 7]} tooltip="hide" change={this.firstComponentChangeValue} value={this.state.firstComponentCurrentValue} />
    <ReactBootstrapSlider max={7} min={1} step={1} ticks={[1, 2, 3, 4, 5, 6, 7]} tooltip="hide" change={this.secondComponentChangeValue} value={this.state.secondComponentCurrentValue} />
}
````

**Comment by ckozin** [comment]
@brownieboy,

Thank you for your response and all your help in attempting to resolve this issue. The issue is that the component is rendered dynamically so I needed to be able to pull the value for each instance. I ended up having to write a function to send the value to an array for the answer and update component with a change of state.
```
eachMultipleRadio: function(multiradio, i){
     var refKey = multiradio.node + "-" + multiradio.number;
     var optionKey = refKey + "-option";
     return (
        <div key={optionKey}>
        <ReactBootstrapSlider max={7} min={1} step={1} ticks={[1, 2, 3, 4, 5, 6, 7]} tooltip="hide"      name="answer" id={refKey} change={this.onChangeValue} value={this.state.currentValue} />
        </div>
     )
},
renderMultipleRadio: function() {
  return (
        <div className={'input-group ' + this.state.hidden}>
              <ul className="list">
                {ma.map(this.eachMultipleRadio)}
              </ul>
       </div>
    )
},
onChangeValue: function(event, value, id){
      var theValue = event.target.value;
      var answer = this.state.checkAnswer;
      var component = this;
      var cid = event.target.id;
      var splitId = cid.split(/-/);
      var nId = splitId[1];
      var nIndex = nId -1;
      answer[nIndex] = theValue.toString();
      component.setState({currentValue:theValue});
      this.changeValue;
    }
```

**Comment by brownieboy** [comment]
Okay, now we're getting somewhere.  I'd still like to see more though - the whole think, ideally.  Can you put it on Github.

In particular, what is in the `ma` array from the line `{ma.map(this.eachMultipleRadio)}`?

**Comment by brownieboy** [comment]
I think that this is your problem:

````JavaScript
component.setState({currentValue:theValue});
````

You have multiple ReactBootstrapSlider components, but they're all trying to share the same value in the state, which is `state.currentValue`.   This needs to be an array, or better still an associative array (aka hash array).  I think you've attempted to address this problem with your state.checkAnswer property.

Here's how I'd do it.  When setting up your state, set up currentValues property as an object, like so:

````JavaScript
getInitialState: function() {
   return {
        currentValues: {}
   };
}
````

Your render method then picks the relevant value from the state.currentValues object by using your refKey as the key to the associative array:
````JavaScript
    <ReactBootstrapSlider
         max={7}
         min={1}
         step={1}
         id={refKey}
         ticks={[1, 2, 3, 4, 5, 6, 7]}
         tooltip="hide"
         change={this.OnChangeValue}
         value={this.state.currentValues[refkey] || 3} />
````

The `|| 3` is a default value, in case `this.state.currentValues[refkey] ` is undefined, which it will be at the start.

Finally, your change handler should do the same thing when setting the state.  I've assumed that id is matched to refKey, as you had it.

````JavaScript
onChangeValue: function(event, value, id){
      var theValue = event.target.value;
      component.setState({currentValue[event.target.id]:theValue});
    }
````

When you've changed some values on your sliders, your state should end up looking something like this:

````JavaScript
{
      currentValues: {
            key1: 3,
            key2: 2,
            key3: 4
      }
}
````

**Comment by brownieboy** [comment]
(Hit the Close button by mistake!)
