### ISSUE TITLE
import slider but hidden

### ISSUE THREAD

**Issue by accateo** [brownieboy/react-bootstrap-slider#18]
Hi, I have imported the slider like in the example:

`import ReactBootstrapSlider from 'react-bootstrap-slider';`

and I have render it in this way:

`  <ReactBootstrapSlider
    value={this.state.currentValue}
    change={this.changeValue}
    slideStop={this.changeValue}
    step={this.state.step}
    max={this.state.max}
    min={this.state.min}
    orientation="vertical"
    reverse={true}
     />`

but I don't see nothing in my page (I set also the state variables). The html code shows that there is this element, but it is not visibile...why?

Thanks

**Comment by brownieboy** [comment]
Have you included the CSS as per the instructions?

**Comment by accateo** [comment]
MMM what CSS? In the guide there is no reference about this...

**Comment by brownieboy** [comment]
The latest release contains instructions about the CSS in the read me:
> You must ensure that you have included bootstrap-slider's CSS file, otherwise the control will be blank! 

Maybe you're looking at an older version?  See also #13.

**Comment by accateo** [comment]
brownie, sorry but also including the css in index file, I have a blank result. I have to import other CSS file?
Thanks

**Comment by JonnyWalker81** [comment]
I have imported the CSS as described in the instructions and it is still blank for me.

**Comment by jaisonjjames** [comment]
> brownie, sorry but also including the css in index file, I have a blank result. I have to import other CSS file?
> Thanks

Having same issue. Did you get any solution?
