### ISSUE TITLE
Slider orientation

### ISSUE THREAD

**Issue by Fiorello** [brownieboy/react-bootstrap-slider#2]
Hi, i'd like to use the slider in vertical mode.
I tried to insert a data attribute "data-slider-orientation", since it is not provided in the component orientation property, but without success.

There is another way?
Thanks

**Comment by brownieboy** [comment]
I've added the orientation prop to version 1.0.1, just published to npmjs.  See updated readme.md for details.

**Comment by Fiorello** [comment]
Great, thanks.

**Comment by brownieboy** [comment]
I've just updated it again to pass even more parameters straight through to seyria's underlying bootstrap-slider component.  (For this, I use the Object Spread Operator that's been proposed for ES2017.)

I haven't tested them all yet, but the `reverse` parameter definitely works, and I have included this in the demo of the vertical slider.
