### ISSUE TITLE
Width of slider

### ISSUE THREAD

**Issue by fabioespinosa** [brownieboy/react-bootstrap-slider#29]
Is there any way to pass in props to ReactBootstrapSlider so that width is no longer fixed to 210px? Thanks!

**Comment by brownieboy** [comment]
The 210px width is set by the CSS in the bootstrap-slider.min.css file, which is part of Seiyria's bootstrap-slider code.   He doesn't appear to be exposing a prop that overrides the width, so I can't really do so either.

You can always, of course, override that CSS wth some higher priority CSS of your own.  Failing that, you'll need to log an issue on the boostrap-slider repository https://github.com/seiyria/bootstrap-slider.

**Comment by fabioespinosa** [comment]
Thank you @brownieboy ! I did end up modifying the bootstrap-slider-min.css file and it worked!

**Comment by x-yuri** [comment]
@brownieboy Probably things have changed. Slider's width is set equal to [original][bs-1] element's [width][bs-2] in case of horizontal orientation. Adding `style={this.props.width}` [here][rbs] resolves the issue. Can that be fixed?

[bs-1]: https://github.com/seiyria/bootstrap-slider/blob/v10.0.0/src/js/bootstrap-slider.js#L432
[bs-2]: https://github.com/seiyria/bootstrap-slider/blob/v10.0.0/src/js/bootstrap-slider.js#L668
[rbs]: https://github.com/brownieboy/react-bootstrap-slider/blob/cff7554e439056b44209b9059f61e454dc690661/src/js/react-bootstrap-slider.jsx#L119
