### ISSUE TITLE
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead

### ISSUE THREAD

**Issue by rodri042** [brownieboy/react-bootstrap-slider#36]
It started to throw that error on console after installing the plugin.
Please fix it :smiley: It's a great library

**Comment by brownieboy** [comment]
That's not an error.  It's a warning.

I assume that you're using React 15.5.x, yes?  If so, you'll be fine for now.  But when React 16 (also know as React Fiber) comes out, then it really might break.

I'll look into it.

**Comment by rodri042** [comment]
Yes, sorry, I used the *error* word.
It's definitely a warning. I'm using 15.5.4.

**Comment by brownieboy** [comment]
Now updated for React 15.5 compatibility and published to npmjs as version 2.0.0.
