### ISSUE TITLE
tooltip prop doesn't take effect

### ISSUE THREAD

**Issue by jborseth** [brownieboy/react-bootstrap-slider#37]
Passing in the tooltip prop doesn't change the value shown in the tooltip. 

Expected: tooltip should show 'foobar'
Actual: tooltip shows the numerical value of the slider's position

This important for adding a label to the numeric value (10+ or $10).

```
        <ReactBootstrapSlider
          value={this.state.currentVal}
          slideStop={this.handleChange}
          step={this.state.step}
          min={this.state.min}
          max={this.state.max}
          tooltip={'foobar'} />
```

Thanks for making this!

**Comment by brownieboy** [comment]
The tooltip prop is not the value that you want to show on the tooltip.  It's a switch that you use to customise _when_ the tooltip is to be displayed.  It can have only one of three values: "show", "hide" or "always".

Please see the upstream documentation at https://github.com/seiyria/bootstrap-slider#options

**Comment by jborseth** [comment]
Thanks for the explanation. I had searched this repo and saw a prop type of string, which is why I thought it worked that way.

For Googler's, I ended up switching to react-rangeslider which allows use of a formatting function to format the tooltip string. https://www.npmjs.com/package/react-rangeslider
