### ISSUE TITLE
Tooltips no longer function with Bootstrap 4

### ISSUE THREAD

**Issue by michael-reeves** [brownieboy/react-bootstrap-slider#38]
I am in the process of upgrading Bootstrap from 3.3.7 to 4.0.  

Apparently the new version uses Tether for tooltips, which I believe I have added to my version of Bootstrap.  

For whatever reason the system used in react-bootstrap-slider no longer displays after the upgrade.

Just a heads up.

I've tried with both ver 1.1.7 and 2.0.0 of react-bootstrap-slider.

**Comment by brownieboy** [comment]
That would be Bootstrap 4 that's been in Alpha for nearly two years?  :wink: 

The bootstrap-slider component would need to be updated to handle Bootstrap 4 before I could do anything with react-booststrap-slider.  Here's a thread on their Github repository where they're discussing that very thing:

https://github.com/seiyria/bootstrap-slider/issues/689

**Comment by michael-reeves** [comment]
Yes.  Leaning WAY forward.  Thanks for the comment.

**Comment by brownieboy** [comment]
@michael-reeves,

There's a couple of suggested CSS fixes for the Bootstrap 4 issue on that bootstrap-slider thread: https://github.com/seiyria/bootstrap-slider/issues/689.  Do want to see if they fix the issue for you?
