### ISSUE TITLE
Slider should be attached to `input` tag

### ISSUE THREAD

**Issue by andhapp** [brownieboy/react-bootstrap-slider#39]
Thanks for creating this.

Currently, `ReactBootstrapSlider` creates a [`div`](https://github.com/brownieboy/react-bootstrap-slider/blob/master/src/js/react-bootstrap-slider.jsx#L96) tag and attaches the slider to this node.

I would like to propose to change this to an `input` tag as that's what the [Bootstrap Slider](https://github.com/seiyria/bootstrap-slider) does and since this is built upon that library, I think it should keep those assumptions in place.

I will be happy to create a PR for the same.

**Comment by brownieboy** [comment]
Yes, please, to creating a PR for this.
