### ISSUE TITLE
Uncaught Error: Invalid input value '2000' passed in

### ISSUE THREAD

**Issue by jwamsterdam** [brownieboy/react-bootstrap-slider#4]
Hi,

For testpurposes I use the following react:

    <ReactBootstrapSlider value='2000' step='1000' max='20000' min='1000' handleChange='' />

But I constantly get the following console error, where my slider is not displaying:

    Uncaught Error: Invalid input value '2000' passed in 

Can anyone help?

**Comment by brownieboy** [comment]
You don't pass props into React components as strings as you're doing.  You have to use curly brackets, e.g.: 

> <ReactBootstrapSlider value={2000} />
