### ISSUE TITLE
Initialize with disabled property has no effect

### ISSUE THREAD

**Issue by matthewma7** [brownieboy/react-bootstrap-slider#44]
```<ReactBootstrapSlider disabled="disabled" />```
Set disabled = "disabled" has no effect at the initial state. 
(Of course, the "disabled" could come from a variable)

**Comment by brownieboy** [comment]
Looks like you're right.

I'm looking into it...

**Comment by brownieboy** [comment]
So I was not checking for the disabled prop in the ComponentDidMount method as I should have been.

Now fixed and rolled out to npmjs.com as version 2.1.2.  I've added a disabled component to my tests too.

Thanks for reporting the error, @matthewma7 .

**Comment by brownieboy** [comment]
Ooops.  I left a debugging console.log() in 2.1.2.  So just published 2.1.3 to remove that.

**Comment by matthewma7** [comment]
@brownieboy Thank you for the fix. It works great. 👍
