### ISSUE TITLE
Plan for supporting Bootstrap 4

### ISSUE THREAD

**Issue by hktonylee** [brownieboy/react-bootstrap-slider#46]
Hi man. I found your work is extremely useful ;-) However it has some display problem in Bootstrap 4. Also there is some problem in detecting the dragging event. Will you have any plan to upgrade it? Thanks.

**Comment by brownieboy** [comment]
See also issue #38.

I cannot do anything with Bootstrap 4 until seirya's bootstrap-slider component is updated to work with it.

**Comment by brownieboy** [comment]
Looks like we have some movement upstream on Bootstrap 4 compatibility:

https://github.com/seiyria/bootstrap-slider/pull/856

Not quite there yet though, but I am keeping an eye on this.  I'll look at a Bootstrap 4 version of this control when this is more stable.

**Comment by mschwartz** [comment]
It seems to be working for me.

However, I do get errors in the console:

[Intervention] Ignored attempt to cancel a touchstart event with cancelabel=false, for exmaple because scrolling is in progress and cannot be interrupted.  bootstrap-slider.js:1627

```
if (ev.preventDefault) {
  ev.preventDefault();
}
```

**Comment by brownieboy** [comment]
Version 3.0.0 just pushed to npmjs.  First support for Bootstrap 4.

Thanks to @DBendit for getting the ball rolling on this.
