### ISSUE TITLE
Reversed props on slider flips the toltips

### ISSUE THREAD

**Issue by pramodsvidyarthi** [brownieboy/react-bootstrap-slider#49]
In a Range slider with two handles when the reversed prop is set to true, it flips the tooltip i.e one tooltip appears on top and another in the bottom, expected both to remain in bottom.

https://codesandbox.io/s/6yrp8pl31r

**Comment by brownieboy** [comment]
I don't do anything with the `reversed`  prop except pass it straight through to Seirya's bootstrap-slider component, so I expect that it's an upstream issue there.
