### ISSUE TITLE
Min and max in same slider: value="[250,450]"

### ISSUE THREAD

**Issue by jwamsterdam** [brownieboy/react-bootstrap-slider#5]
Hi, in the docs of seiyria I can read that there is an option to place two dots in the slider, by setting the value by an array.. 

Unfortunately, I am unable to get this to work.. Is this supported?

I get the following error: Uncaught TypeError: num.toFixed is not a function

**Comment by kellyi** [comment]
This seems to work if you use an array of two numbers, like `[1,10]` as the `value` prop instead of a single number.

**Comment by brownieboy** [comment]
@kellyi is right.  Passing an array of two values does work.  In that case you get an array of two values as the return value, and you just need split them out from the returned array in your callback handler.

In a future version, I'll update the demo code to give an example of a dual slider.  The actual react-bootstrap-slider code itself requires no changes.

One quirk that I noticed is that it's possible to drag the "min" slider handler to actually have a higher value than the "max" handler.  This seems a bit odd to me, but it's what happens in @seiyria's [own example] (http://seiyria.com/bootstrap-slider/) (see his Example 2).

**Comment by seiyria** [comment]
It's not so much min and max as it is left handle and right handle. I think when one value surpasses the other, their positions in the array change, but don't quote me on that.

**Comment by brownieboy** [comment]
Yes, I see it now.  When they cross over, they actually swap values.  Neat!
