### ISSUE TITLE
API weirdness

### ISSUE THREAD

**Issue by BenjaminVanRyseghem** [brownieboy/react-bootstrap-slider#51]
Hi,

first of all, thanks for your project, it's cool :smile:

But I find that the API is a bit different from what is currently seen:

- `disabled` taking a string is quite unconventional, and leads to unnecessary ternary operations
- `change` and `slideStop`: events callback names usually start with `on` to tell they expect callbacks, like `onChange`, `onClick` etc

Just my 2cts,
have a great day

**Comment by brownieboy** [comment]
You're welcome to put in a PR to change things to how you like them, as long as you can do it in a way that doesn't break the existing API.

E.g. change the methods to `onChange` and `onSlideStop`, and then have `change` and `slideStop` be aliases to those.
