### ISSUE TITLE
react-bootstrap-slider requires react^16.0.0

### ISSUE THREAD

**Issue by mbrennan** [brownieboy/react-bootstrap-slider#53]
Ever since react-bootstrap-slider v2.1.1, the package requires react^16.0.0 to be installed as a peer dependency.  Is this actually the case?  It seems to work fine even though I'm using react 15.6.1.

**Comment by brownieboy** [comment]
React 16.0.0 is the last version under which the package was tested.

No, that doesn't mean that it won't run under earlier versions, but just that this has not been tested.
