### ISSUE TITLE
Npm version 2.2.1 references babel runtime libs by absolute path

### ISSUE THREAD

**Issue by mauron85** [brownieboy/react-bootstrap-slider#55]
Latest npm package is somehow broken.
When you check https://github.com/brownieboy/react-bootstrap-slider/blob/master/dist/react-bootstrap-slider.js#L3

All requires of babel runtime libs include full path:
`/Users/michaelbrown/Development/react-bootstrap-slider`

**Comment by brownieboy** [comment]
Thanks for the report.  I'm looking into this...

**Comment by brownieboy** [comment]
I think I  have a fix for this now.  Hopefully, I'll release today after some further testing.
