### ISSUE TITLE
Version 1.0.1 and up fails if babel-cli is not installed globally

### ISSUE THREAD

**Issue by janmeier** [brownieboy/react-bootstrap-slider#6]
```
> react-bootstrap-slider@1.0.2 postinstall /home/jan/src/snap/frontend/app/node_modules/react-bootstrap-native-slider/node_modules/react-bootstrap-slider
> npm run buildDemo

-
> react-bootstrap-slider@1.0.2 buildDemo /home/jan/src/snap/frontend/app/node_modules/react-bootstrap-native-slider/node_modules/react-bootstrap-slider
> npm run build && webpack

/
> react-bootstrap-slider@1.0.2 build /home/jan/src/snap/frontend/app/node_modules/react-bootstrap-native-slider/node_modules/react-bootstrap-slider
> babel ./src/js/react-bootstrap-slider.jsx -o ./dist/react-bootstrap-slider.js

sh: 1: babel: not found
```

The commands in postinstall should be `./node_modules/.bin/babel` or similar. 

As an addendum, is there are reason to re-build on `postInstall`? The published package is already built

**Comment by brownieboy** [comment]
Odd.  I didn't get that error, and I don't have babel-cli installed globally.

Never the less, I'll amend the path in the `build` script, as per your suggestion.  I'll drop the `postinstall` script too because, as you say, it's not really needed.

**Comment by janmeier** [comment]
Very odd indeed - I tried installing in a clean project, and got the same error ... I'm running node 4.4.5 and npm 2.15.5

Thanks :)

**Comment by janmeier** [comment]
Can I bug you to publish a new version as well

**Comment by brownieboy** [comment]
Version 1.0.3 just published.
