### ISSUE TITLE
Set attributes dynamically

### ISSUE THREAD

**Issue by SunSunKu** [brownieboy/react-bootstrap-slider#67]
Is there a way to set or add attributes dynamically? For example, like after the slideStop event? Thanks!

**Comment by brownieboy** [comment]
I'm not quite sure what you're trying to achieve.  Could you give a code example of how you think it ought to work?

**Comment by SunSunKu** [comment]
Sorry for the delay in responding! I will look to respond with more information sometime next week. Thanks!

**Comment by SunSunKu** [comment]
Hi! What I was looking for was for a coding assessment and has been resolved. Thanks!
