### ISSUE TITLE
Does react-bootstrap-slider support slider ticks?

### ISSUE THREAD

**Issue by ahmethudaiaydin** [brownieboy/react-bootstrap-slider#69]
Hi,
[Bootstrap slider](https://github.com/seiyria/bootstrap-slider) supports slider ticks and label as shown in [examples #13](https://seiyria.com/bootstrap-slider)
Example usage is like:
`<input id="ex13" type="text" data-slider-ticks="[0, 100, 200, 300, 400]" data-slider-ticks-snap-bounds="30" data-slider-ticks-labels='["$0", "$100", "$200", "$300", "$400"]'/>`

Does react-bootstrap-slider support it? If not, is there any plan to add it?

Thanks

**Comment by brownieboy** [comment]
Ticks are supported.  Have you tried it?
