### ISSUE TITLE
Does react-bootstrap-slider take ticks, tick_positions, and tick_labels as properties?

### ISSUE THREAD

**Issue by bhutaninitin** [brownieboy/react-bootstrap-slider#7]
Does react-bootstrap-slider take ticks, tick_positions, and tick_labels as props? If so, does it render correctly when these values change?

**Comment by brownieboy** [comment]
Any props that you pass into react-bootstrap-slider should be passed on to the underlying bootstrap-slider component.

Whether they'll render correctly is not something that I've tested.  Maybe you could give it a try and report back here what you find.

**Comment by bhutaninitin** [comment]
Well..they do not seem to work..The following does not generate correctly and breaks other sliders on the page:
&lt;ReactBootstrapSlider value={this.state.currrecsiz}
    ticks={[0, 256, 4080, 262144, 524288, 786432, 1048576]}
    ticks_positions={[0, 10, 35, 58, 72, 85, 100]}
    ticks_labels={['0', 'Default', '4080B', '.25', '.5', '.75', '1 MiB']}
       ticks_snap_bounds={1048576}
        /&gt;

**Comment by brownieboy** [comment]
Okay.  I'll take a look when I get a moment.

**Comment by brownieboy** [comment]
Version 1.0.6, just pushed to npmjs, fixes the issue where ticks props were not being rendered.  This was by the code was assuming that there would always be `min` and `max` props, but the `ticks` props actually override these

**Comment by mastef** [comment]
Seems like they're not updating though @brownieboy
