### ISSUE TITLE
CSS not built in dist js file.

### ISSUE THREAD

**Issue by dmason30** [brownieboy/react-bootstrap-slider#9]
The slider isn't display for me using 1.0.6. No styles appear to be getting loaded? @brownieboy 

        <ReactBootstrapSlider
                    value={100}
                    handleChange={() => {}}
                    step={[]}
                    max={100}
                    min={0}
                    orientation="horizontal"
                    reverse={false}
                    disabled={false} />

**Comment by jeffling** [comment]
instructions say you need to include it from bootstrap-slider package

**Comment by brownieboy** [comment]
Actually, I only recently updated the instructions to say that you need to include the CSS.  Please see https://github.com/brownieboy/react-bootstrap-slider/issues/13.
